### ISSUE TITLE
Where to find spatial data-- external links & add lesson?

### ISSUE THREAD

**Issue by mjones01** [datacarpentry/r-spatial-data-management-intro#6]
These resources were listed in the original lessons and I don't want to loose them 
Finding spatial data might  be an interesting lesson 07 -- perhaps to be taught at the very end of a workshop AFTER the other lesson series?  Or at the end of this series for self-paced tutorials? 

resources:
Finding Data
DataOne - www.dataone.org/find-data
Government / Federal Agency data:
www.data.gov/
www.geoplatform.gov/
State and local data, such as : www.data.ny.gov/
ecologicaldata.org
Finding/reading metadata:
https://www.fgdc.gov/metadata
http://geology.usgs.gov/tools/metadata/tools/doc/faq.html

**Comment by mjones01** [comment]
Possible objective (from original lessons): 
Understand that spatial data are generally available on web sites via some download protocol

**Comment by lwasser** [comment]
I think what might make sense from a teaching perspective is to introduce this in L01. Because the workflow is -

you have a question and then need to figure out data to answer the question. (ideally).
So a nice segway might be explaining how these data were found and selected. Then at the bottom of the lesson we can have a resources section with links to other data providers (NEON is one but that list above is pretty limited - we can add lots more easily). National map, USGS EOS, etc etc.

Remember the key here is not "phenology" it's understanding what a typical data workflow might look like if you had a science question that happens to be phenology. I think this will be perfect.

**Comment by mjones01** [comment]
These have all be incorporated into L00 with PR #7.  Closing comment.
